### ISSUE TITLE
Appears to be two timing issues w/PGMoon

### ISSUE THREAD

**Issue by BeccaMorn** [dlebansais/PgMoon#3]
The first issue has to do with tracking DST. PGMoon, since the switch to Standard Time for winter in the US, has been setting server reset time an hour early. (23:00 EST rather than midnight.)

The second issue just cropped up on 15 Jan 2022. The program says that the current Full Moon starts at midnight EST 17 January, when in fact it already switched to the full moon as of the previous day, midnight EST 16 January. It appears to have lost a day in its calculations.

Combined, it's saying that the full moon in PG is to start at 23:00 on 16 January, which is 25 hours off from in-game time.

cheers,
Kadera (in PG)

**Comment by dlebansais** [comment]
Yes, there was a conjunction of time uncertainties this phase. I can't fix the discrepancy between the game formula and mine, but they are following each other pretty closely. Except when daylight saving time difference hits.
This problem should not happen again for a few years (though I didn't check). And I don't dare fix the 1h difference for fear of messing up the rest.

**Comment by BeccaMorn** [comment]
Regarding the 1 hour DST-related discrepancy, that's fine--I'd actually gotten used to mentally adjusting the time ahead by 1 hour during Standard Time. I take it you're saying that the current full moon discrepancy (off by a full day, issue 2) will resolve itself at some point during an upcoming phase? I'd a feeling the just-ended Waxing Gibbous phase (11-17 Jan) did seem overlong.

**Comment by dlebansais** [comment]
Yes. Unless I made a big mistake, the next phase will also start one day earlier than displayed (since full moon lasts 3 days), and thing should return to normal after that. Hopefully for years.

**Comment by BeccaMorn** [comment]
Sounds good -- and thank you for both this and your excellent Surveyor program. I'll close this issue.
